### ISSUE TITLE
Conversation flow in botkit

### ISSUE THREAD

**Issue by skprasadu** [ramswaroop/botkit#2]
Hi Ram,

Is there a way I can implement a conversation flow similar to javascript botkit framework. Can you provide me any hint of how to implement this.

Krishna

**Comment by skprasadu** [comment]
Ram,

Thanks for getting back to me, as you can see, I took your code and embedded in my application and it works like a charm. Ideally, I want to include your framework as a maven repo in a Spring Boot application. Please provide few examples how to use your botkit as a part of maven repo.

Thanks
Krishna

**Comment by ramswaroop** [comment]
Hi Krishna,

Yes, you can easily include this project as a maven dependency after Botkit is released to the central repository. I will include a sample in README file as well.

**Comment by ramswaroop** [comment]
Hi Krishna,

I am happy to tell you that I have added the conversation feature as you requested. Do let me know if find any bugs or you get stuck somewhere.

Hope it helps you! 

Thanks,
Ram
