### ISSUE TITLE
Joining a channel?

### ISSUE THREAD

**Issue by hdt80** [ramswaroop/botkit#3]
I'm probably just missing this, but how can I get my bot to join a channel and listen to messages from that channel?

**Comment by ramswaroop** [comment]
Hi,

Thanks for reaching out. You can make your bot join a channel but just inviting it to the channel by typing `/invite @botname` or programmatically you can use this [method](https://api.slack.com/methods/channels.join) which is part of slack web api. It's just a `GET` call that you have to make.

Hope it makes things clear!

**Comment by hdt80** [comment]
I wasn't aware it was this simple. Thanks for the quick response!

**Comment by ramswaroop** [comment]
No problem @hdt80 :)

**Comment by ramswaroop** [comment]
Hey, I recently found this http://stackoverflow.com/questions/29309114/how-to-join-a-slack-channel-as-a-real-time-messaging-bot-user. If this is true then my first answer is correct but the 2nd isn't (JFYI).
