### ISSUE TITLE
Installation from Maven dependency hangs

### ISSUE THREAD

**Issue by jameslmartin** [ramswaroop/botkit#5]
I'm trying to include BotKit in a Maven project but when I run `mvn install` or `verify`, it appears to hang while downloading:

```
Downloading: http://repo.spring.io/ext-release-local/org/jboss/shrinkwrap/shrinkwrap-bom/1.2.2/shrinkwrap-bom-1.2.2.pom
```

Is there a mismatch on versioning? In the `pom.xml`, I've included the dependency as listed in the README and the project (a fresh maven project) installs fine without listing it as a dependency. Any thoughts on debugging? Perhaps I'm being impatient? 

I will try cloning the project and build from source for the time being.

**Comment by ramswaroop** [comment]
Hi,

Maybe you have a lot of transitive dependency in your `pom.xml` file. Can you post the out of this command `mvn dependency:tree` here?
