### ISSUE TITLE
How to use SlackWebhooks?

### ISSUE THREAD

**Issue by mboujonnier** [ramswaroop/botkit#6]
Can you give a little example of how to use SlackWebhooks ?
When I tried it seems slackIncomingWebhookUrl is not initialized by Spring... I forgot something but I don't know what..

Thanks !

**Comment by ramswaroop** [comment]
Hi,

I have given an example of Incoming webhooks [here](https://github.com/ramswaroop/botkit/blob/master/src/main/java/me/ramswaroop/botkit/slackbot/SlackWebhooks.java). Please put the correct url in [application.properties](https://github.com/ramswaroop/botkit/blob/master/src/main/resources/application.properties) file and then run the app.

Incoming webhooks are nothing but an endpoint given by slack to which we `POST` messages.

**Comment by mboujonnier** [comment]
yes this is the one I'm using but it triggers an exception (Caused by: java.lang.IllegalArgumentException: URI must not be null) as 
```
 @Value("${slackIncomingWebhookUrl}")
 private String slackIncomingWebhookUrl;
```

is not populated (but the url is set in application.property according to the url given by slack (slackIncomingWebhookUrl=https://hooks.slack.com/services/T1...)

So I was wondering how to use it properly.

Thanks

**Comment by ramswaroop** [comment]
Can you tell me how are you using Botkit? Have you cloned the repo and using it or as a dependency?

**Comment by mboujonnier** [comment]
I just cloned it and I modified the onReceiveDM call to trigger the Slack webhook:

`   
    @Controller(events = {EventType.DIRECT_MENTION, EventType.DIRECT_MESSAGE})
    public void onReceiveDM(WebSocketSession session, Event event) {
        reply(session, event, new Message("Hi, I am " + currentUser.getName()));
        SlackWebhooks wh = new SlackWebhooks();
        wh.invokeSlackWebhook();
    }
`

But I guess Spring should instanciate SlackWebhooks, not my code but I don't know how. The last time I used Spring, there was an XML file :)

**Comment by mboujonnier** [comment]
Ok I found how to make it working. 
I have added 

```
    @Autowired
    SlackWebhooks slackWebhooks;
```

Sorry for the dumb question.

**Comment by ramswaroop** [comment]
Hey,

There's no dumb question. In case if you've not understood the mistake here, when you instantiate an object yourself then spring doesn't inject the dependencies. That's the reason you were getting `null` url.

Hope you got the concept.

**Comment by mboujonnier** [comment]
yep, just needed to refresh+update my Spring memories.
