### ISSUE TITLE
How to save state in a conversation?

### ISSUE THREAD

**Issue by mboujonnier** [ramswaroop/botkit#8]
Currently there is no real conversation object, so I did not find how to attach data to a conversation to keep tracks of what was said between steps.

Did I miss something ?

**Comment by ramswaroop** [comment]
Hi,

You chain methods in a conversation so when a method is invoked then all the methods in the line to which it was chained would have been invoked already one after the other.

So, why you want to keep track of whats being said earlier. Can you please give a use case?

**Comment by mboujonnier** [comment]
There are a lot of usecases... considering your example (scheduling a meeting), in a real project, I would probably create a Schedule object to handle the schedule and at each step of the conversation, I will update it so I need a way to retrieve it. So store it in the conversation as a cache would be simple.

Then, when fully populated, I may store it in a DB or whatever.

**Comment by ramswaroop** [comment]
You can update your Schedule object inside each controller method. Why do you need to retrieve your conversation?

**Comment by mboujonnier** [comment]
How do you retrieve the Schedule object ? They can be plenty.... so yes I implemented my own conversation class to store all stuff saved from a conversation between a bot and a user. But so now I have duplicate code...
```
    @Controller(events = {EventType.DIRECT_MENTION, EventType.DIRECT_MESSAGE}, pattern = "create meeting", next = "setMeetingName")
    public void createMeeting(WebSocketSession session, Event event) 
    {
        startConversation(event, "setMeetingName");   // start conversation
        Conversation conv = new Conversation(session.getId());
        conversations.put(conv.getId(), conv);
        
        reply(session, event, new Message("With pleasure, what's the meeting name ?"));
    }
```

**Comment by ramswaroop** [comment]
This code is not correct. You should have your `Conversation` as an instance variable and not declared and initialized locally.

**Comment by mboujonnier** [comment]
That means that one SlackBot instance is created for each discussion ?

**Comment by ramswaroop** [comment]
Nope. We can discuss further on gitter. That would be better I suppose.

**Comment by sigrist** [comment]
What was the resolution for this issue? I'm having the same question here, but I couldn't find anything in the documentation and I can't join the gitter channel to search the discussion.

**Comment by rampatra** [comment]
@sigrist You can follow a similar approach as @mboujonnier did. You can have an object to store session and pass it around the conversation methods.
