### ISSUE TITLE
Some attributes in Event are not populated

### ISSUE THREAD

**Issue by mboujonnier** [ramswaroop/botkit#9]
`getUser()` in event returns `null`. In other words, `user` in `event` isn't set.

**Comment by ramswaroop** [comment]
If you go through the README file carefully, you can find:

> Points to Note:
> 
> Event, Message and RichMessage are generic models. Not all the time, all the attributes present in them will have values. In other words, Slack sends different responses for different events.
> You need a channel id to send replies. Therefore, you can use reply() method for events which have a channel id in them or else you have to explicitly set the channel id in the Message object.
>

**Comment by mboujonnier** [comment]
Not sure I understood.... so User in event will never be populated based on the UserId ?

**Comment by ramswaroop** [comment]
For events like [team_join](https://api.slack.com/events/team_join), the user object will be populated and for events like [message](https://api.slack.com/events/message), there is no user object returned by slack but just the user id. So, `event` will only have value in `userId` field but not in `user` field.

**Comment by mboujonnier** [comment]
So I need to implement my own API call to retrieve the user using https://slack.com/api/users.info API ?
That kills the fun :)

**Comment by ramswaroop** [comment]
Nope, I will provide APIs to access all basic information in the next release. Don't worry.
